"""add external API fields to cards

Revision ID: 09cd825d5e33
Revises: ca0dab974708
Create Date: 2026-02-21 12:10:56.156814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09cd825d5e33'
down_revision = 'ca0dab974708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_api_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('external_image_url', sa.String(length=500), nullable=True))
        batch_op.create_index('idx_card_external_api_id', ['external_api_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index('idx_card_external_api_id')
        batch_op.drop_column('external_image_url')
        batch_op.drop_column('external_api_id')

    # ### end Alembic commands ###
