"""Add chapter field to book_quote table

Revision ID: 16c20e5464a8
Revises: 208f00b27703
Create Date: 2025-12-17 12:03:18.710849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c20e5464a8'
down_revision = '208f00b27703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_quote', schema=None) as batch_op:
        batch_op.drop_column('chapter')

    # ### end Alembic commands ###
