"""add external market data to cards

Revision ID: 1b2766d5305f
Revises: 09cd825d5e33
Create Date: 2026-02-21 12:55:36.687593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2766d5305f'
down_revision = '09cd825d5e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_market_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('external_market_data')

    # ### end Alembic commands ###
