"""Initial migration with correct field lengths

Revision ID: 1bacb1a8b3da
Revises: 
Create Date: 2025-11-15 21:12:58.144878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bacb1a8b3da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artworks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('artist', sa.String(length=200), nullable=True),
    sa.Column('after', sa.String(length=200), nullable=True),
    sa.Column('year', sa.String(length=100), nullable=False),
    sa.Column('series', sa.String(length=500), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('medium', sa.Text(), nullable=True),
    sa.Column('collections', sa.Text(), nullable=True),
    sa.Column('site_approved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.String(length=50), nullable=False),
    sa.Column('quote_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('additional_authors', sa.Text(), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('isbn13', sa.String(length=20), nullable=True),
    sa.Column('my_rating', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('number_of_pages', sa.Integer(), nullable=True),
    sa.Column('original_publication_year', sa.Integer(), nullable=True),
    sa.Column('date_read', sa.String(length=20), nullable=True),
    sa.Column('date_added', sa.String(length=20), nullable=True),
    sa.Column('bookshelves', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('my_review', sa.Text(), nullable=True),
    sa.Column('private_notes', sa.Text(), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('owned_copies', sa.Integer(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_name', sa.String(length=100), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('artist_palette', sa.String(length=1000), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('model_version', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liked_artworks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artwork_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'artwork_id')
    )
    op.create_table('movies',
    sa.Column('tmdb_id', sa.String(), nullable=False),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('letterboxd_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('director', sa.String(length=200), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('my_rating', sa.Integer(), nullable=True),
    sa.Column('date_watched', sa.String(length=20), nullable=True),
    sa.Column('my_review', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('collections', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('tmdb_id')
    )
    op.create_table('playlists',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('playlist_owner', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('album_art', sa.String(), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=True),
    sa.Column('is_collab', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('site_approved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('date_reviewed', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tv_shows',
    sa.Column('tvdb_id', sa.String(), nullable=False),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('my_rating', sa.Integer(), nullable=True),
    sa.Column('date_finished', sa.String(length=20), nullable=True),
    sa.Column('last_watched', sa.String(length=20), nullable=True),
    sa.Column('my_review', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('collections', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('tvdb_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('tv_shows')
    op.drop_table('reviews')
    op.drop_table('playlists')
    op.drop_table('movies')
    op.drop_table('liked_artworks')
    op.drop_table('generated_images')
    op.drop_table('collections')
    op.drop_table('books')
    op.drop_table('book_quote')
    op.drop_table('artworks')
    # ### end Alembic commands ###
