"""Add is_visible to book_pairing

Revision ID: 47344028237d
Revises: 639c1e787a0f
Create Date: 2025-12-30 12:32:34.539191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47344028237d'
down_revision = '639c1e787a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_pairing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_pairing', schema=None) as batch_op:
        batch_op.drop_column('is_visible')

    # ### end Alembic commands ###
