"""Add pins and alcohol_labels tables for collecting module

Revision ID: 4b82ff45e261
Revises: 820de944fb76
Create Date: 2025-11-17 19:49:27.984888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b82ff45e261'
down_revision = '820de944fb76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alcohol_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('alcohol_volume', sa.String(length=50), nullable=True),
    sa.Column('alcohol_proof', sa.Integer(), nullable=True),
    sa.Column('alcohol_type', sa.String(length=50), nullable=True),
    sa.Column('dimensions', sa.String(length=50), nullable=True),
    sa.Column('distributed_by', sa.String(length=200), nullable=True),
    sa.Column('distributed_by_location', sa.String(length=200), nullable=True),
    sa.Column('bottled_by', sa.String(length=200), nullable=True),
    sa.Column('bottled_by_location', sa.String(length=200), nullable=True),
    sa.Column('distilled_by', sa.String(length=200), nullable=True),
    sa.Column('distilled_by_location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('origin', sa.String(length=200), nullable=True),
    sa.Column('owned', sa.Boolean(), nullable=True),
    sa.Column('sold', sa.Boolean(), nullable=True),
    sa.Column('image_filename', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('pin_type', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('associated_person', sa.String(length=200), nullable=True),
    sa.Column('origin', sa.String(length=200), nullable=True),
    sa.Column('owned', sa.Boolean(), nullable=True),
    sa.Column('sold', sa.Boolean(), nullable=True),
    sa.Column('dimensions', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('reproduction', sa.Boolean(), nullable=True),
    sa.Column('original_year', sa.String(length=20), nullable=True),
    sa.Column('links', sa.Text(), nullable=True),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('number_in_set', sa.Integer(), nullable=True),
    sa.Column('image_filename', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pins')
    op.drop_table('alcohol_labels')
    # ### end Alembic commands ###
