"""Replace FeaturedBook with BookPairing

Revision ID: 639c1e787a0f
Revises: 2a7c04e7ae36
Create Date: 2025-12-30 11:26:49.747131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '639c1e787a0f'
down_revision = '2a7c04e7ae36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_pairing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id_1', sa.Integer(), nullable=False),
    sa.Column('book_id_2', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id_1'], ['books.id'], ),
    sa.ForeignKeyConstraint(['book_id_2'], ['books.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('featured_book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('featured_book',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('featured_book_book_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('featured_book_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('featured_book_pkey'))
    )
    op.drop_table('book_pairing')
    # ### end Alembic commands ###
