"""Add is_public flag to artwork_galleries

Revision ID: 820de944fb76
Revises: 3fd1d7f0cfa8
Create Date: 2025-11-17 16:32:19.782819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820de944fb76'
down_revision = '3fd1d7f0cfa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    with op.batch_alter_table('artwork_galleries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE artwork_galleries SET is_public = TRUE WHERE is_public IS NULL")

    # Now make it NOT NULL
    with op.batch_alter_table('artwork_galleries', schema=None) as batch_op:
        batch_op.alter_column('is_public', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork_galleries', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
