"""Add Author and PublicationAuthor tables, refactor publications

Revision ID: cafb09c62235
Revises: cd2e181234de
Create Date: 2025-11-17 10:11:28.769421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cafb09c62235'
down_revision = 'cd2e181234de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_you', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('publication_authors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('publication_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('author_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_column('authors')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authors', sa.TEXT(), autoincrement=False, nullable=False))

    op.drop_table('publication_authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
