"""Add publications table for writing section

Revision ID: cd2e181234de
Revises: 1bacb1a8b3da
Create Date: 2025-11-17 09:43:42.108710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2e181234de'
down_revision = '1bacb1a8b3da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('venue', sa.String(length=500), nullable=False),
    sa.Column('publication_date', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('pmid', sa.String(length=50), nullable=True),
    sa.Column('volume_issue', sa.String(length=100), nullable=True),
    sa.Column('badge', sa.String(length=200), nullable=True),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publications')
    # ### end Alembic commands ###
