"""Add movie quotes and content pairings tables

Revision ID: cf6f100f43d7
Revises: f30f9fc9d997
Create Date: 2026-02-06 09:51:47.870167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6f100f43d7'
down_revision = 'f30f9fc9d997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.String(length=50), nullable=False),
    sa.Column('quote_text', sa.Text(), nullable=False),
    sa.Column('character', sa.String(length=200), nullable=True),
    sa.Column('scene_timestamp', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_pairing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type_1', sa.String(length=20), nullable=False),
    sa.Column('item_id_1', sa.String(length=50), nullable=False),
    sa.Column('item_type_2', sa.String(length=20), nullable=False),
    sa.Column('item_id_2', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liked_movie_quotes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['movie_quote.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'quote_id')
    )
    # ### end Alembic commands ###

    # Migrate existing BookPairing data into ContentPairing
    conn = op.get_bind()
    book_pairings = conn.execute(
        sa.text('SELECT id, book_id_1, book_id_2, note, is_visible, updated_at, updated_by FROM book_pairing')
    ).fetchall()
    for bp in book_pairings:
        conn.execute(
            sa.text(
                'INSERT INTO content_pairing (item_type_1, item_id_1, item_type_2, item_id_2, note, is_visible, updated_at, updated_by) '
                'VALUES (:type1, :id1, :type2, :id2, :note, :visible, :updated_at, :updated_by)'
            ),
            {
                'type1': 'Book', 'id1': str(bp.book_id_1),
                'type2': 'Book', 'id2': str(bp.book_id_2),
                'note': bp.note, 'visible': bp.is_visible,
                'updated_at': bp.updated_at, 'updated_by': bp.updated_by,
            }
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liked_movie_quotes')
    op.drop_table('content_pairing')
    op.drop_table('movie_quote')
    # ### end Alembic commands ###
