"""Add card collection tables

Revision ID: f30f9fc9d997
Revises: 47344028237d
Create Date: 2026-01-11 11:32:10.126441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30f9fc9d997'
down_revision = '47344028237d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('set_name', sa.String(length=200), nullable=True),
    sa.Column('set_year', sa.Integer(), nullable=True),
    sa.Column('card_number', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('variant', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index('idx_card_brand', ['brand'], unique=False)
        batch_op.create_index('idx_card_category', ['category'], unique=False)
        batch_op.create_index('idx_card_name', ['name'], unique=False)
        batch_op.create_index('idx_card_set', ['set_name', 'set_year'], unique=False)

    op.create_table('card_copies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('is_graded', sa.Boolean(), nullable=True),
    sa.Column('grading_service', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('storage_type', sa.String(length=30), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('image_front_url', sa.String(length=500), nullable=True),
    sa.Column('image_back_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_acquired', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_copies', schema=None) as batch_op:
        batch_op.create_index('idx_copy_featured', ['is_featured'], unique=False)
        batch_op.create_index('idx_copy_storage', ['storage_location'], unique=False)
        batch_op.create_index('idx_copy_visibility', ['visibility'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_copies', schema=None) as batch_op:
        batch_op.drop_index('idx_copy_visibility')
        batch_op.drop_index('idx_copy_storage')
        batch_op.drop_index('idx_copy_featured')

    op.drop_table('card_copies')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index('idx_card_set')
        batch_op.drop_index('idx_card_name')
        batch_op.drop_index('idx_card_category')
        batch_op.drop_index('idx_card_brand')

    op.drop_table('cards')
    # ### end Alembic commands ###
